# Generated by Django 5.2 on 2025-04-28 16:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Описание', max_length=200, null=True)),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='Цена')),
            ],
        ),
        migrations.CreateModel(
            name='Habits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Название привычки', max_length=50, null=True)),
                ('place', models.CharField(help_text='Место в котором необходимо выполнять действие.', max_length=100)),
                ('time', models.TimeField(help_text='Время, когда не обходимо выполнять действие.')),
                ('action', models.CharField(help_text='Само действие', max_length=250)),
                ('pleasant_habits_sign', models.BooleanField(default=False, help_text='Признак приятной привычки')),
                ('periodicity', models.IntegerField(default=2, help_text='Периодичность(в днях)')),
                ('time_to_complete', models.DurationField(default=datetime.time(0, 1), help_text='Время на выполнение')),
                ('is_public', models.BooleanField(default=False, help_text='Признак публичности')),
            ],
        ),
    ]
